version: "2"

services:
  clickhouse:
    image: yandex/clickhouse-server:21.3
    volumes:
      - ./scripts/clickhouse:/docker-entrypoint-initdb.d
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - 8123:8123
      - 9000:9000
