// Code generated by mockery v1.0.0. DO NOT EDIT.

package ballistic

import mock "github.com/stretchr/testify/mock"

// MockDumper is an autogenerated mock type for the Dumper type
type MockDumper struct {
	mock.Mock
}

// Dump provides a mock function with given fields: query, rows
func (_m *MockDumper) Dump(query string, rows [][]interface{}) {
	_m.Called(query, rows)
}

// Return provides a mock function with given fields:
func (_m *MockDumper) Return() (bool, string, []interface{}) {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func() string); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 []interface{}
	if rf, ok := ret.Get(2).(func() []interface{}); ok {
		r2 = rf()
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).([]interface{})
		}
	}

	return r0, r1, r2
}
